### ISSUE TITLE
[1.6.8] top icons nott showing

### ISSUE THREAD

**Issue by ROMthesheep** [jeffThompson/DarkArduinoTheme#8]
hello,
in the version 1.6.8 the top icons doesnt appear at all
here is a screenshots:
[https://i.gyazo.com/ad0976d4bb0e49d8c5f278f7b0ddb949.png](img)

edit:
i changed some files(the syntax folder and the theme.txt) and i solve the issue
great theme, realy nice work

**Comment by BStricklin** [comment]
Would you mind posting your change as a fork? I have the same problem.

**Comment by ROMthesheep** [comment]
@BStricklin ok, np mate

**Comment by TheBeardedMan** [comment]
@ROMthesheep What file under the syntax folder did you change, and what did you change in those files? I'm having the same issue and cannot find a fix.

**Comment by Josephc3** [comment]
I have found the same issue and have found a fix, the file extensions need to be .png now not .gif 
i have a fork that has it fixed, and have put in a pull request

**Comment by Rinksrides2013** [comment]
Fix confirmed on Win 7 pro x64, IDE 1.6.9 nightly. 
just replaced the theme folder in C:\arduino-nightly-windows\arduino-nightly\lib\ with the dark theme folder, 
renamed all *.gif files with *.png extension inside C:\arduino-nightly-windows\arduino-nightly\lib\theme and IDE buttons works now. Your folders might be in different locations if not using the nightly.

**Comment by n1stvn** [comment]
I can confirm the same.
Renaming the files to .png fixed the msising buttons

**Comment by jeffThompson** [comment]
Thanks all, sorry for the delay on my end! Button files updated; old GIF buttons still there in case you need them.

Can someone confirm the new buttons work?

**Comment by IdanSagiv** [comment]
Hey Jeff –

I love the look of your IDE up here in the picture, but the got used to another one..
i have been using [this:](https://github.com/technobly/MonokaiArduinoTheme) theme since i found it a year ago, but the latest release [(**1.7.10**):](http://www.arduino.org/downloads)
 breaks it.
Can you possibly update or help me to help myself update it?

The IDE simply crashes out if i try and use the theme.

Thanks!
Idan

**Comment by IdanSagiv** [comment]
Hey Jeff –

I love the look of your IDE in the picture, but i got used to another one..
i have been using [this:](https://github.com/technobly/MonokaiArduinoTheme) theme since i found it a year ago, but the latest release [(**1.7.10**):](http://www.arduino.org/downloads)
 breaks it.
Can you possibly update or help me to help myself update it?

The IDE simply crashes out if i try and use the theme.

Thanks!
Idan

**Comment by jeffThompson** [comment]
@IdanSagiv – you'll need to post your issue on that repo, can't help you with it here :)

**Comment by IdanSagiv** [comment]
O.k, i did it myself already..

https://github.com/IdanSagiv/DarkArduinoTheme-master

​​
Have fun..

2016-06-06 19:40 GMT+03:00 Jeff Thompson <notifications@github.com>:
